name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Building
        run: make -j releases

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          draft: true
